export const POPULAR_CURRENCIES = ["USD", "EUR", "GBP", "CHF", "JPY"];

export const CURRENCY_SYMBOLS: Record<string, string> = {
  THB: "฿",
  USD: "$",
  AUD: "A$",
  HKD: "HK$",
  CAD: "C$",
  NZD: "NZ$",
  SGD: "S$",
  EUR: "€",
  HUF: "Ft",
  CHF: "Fr",
  GBP: "£",
  UAH: "₴",
  JPY: "¥",
  CZK: "Kč",
  DKK: "kr",
  ISK: "kr",
  NOK: "kr",
  SEK: "kr",
  RON: "lei",
  TRY: "₺",
  ILS: "₪",
  CLP: "$",
  PHP: "₱",
  MXN: "$",
  ZAR: "R",
  BRL: "R$",
  MYR: "RM",
  IDR: "Rp",
  INR: "₹",
  KRW: "₩",
  CNY: "¥",
  XDR: "SDR",
};
